# Generated by Django 2.2.11 on 2020-03-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepthOneKeyword',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'depth_one_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepthOneRel',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('relkeyword', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'depth_one_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepthThreeKeyword',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'depth_three_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepthThreeRel',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('relkeyword', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'depth_three_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepthTwoKeyword',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'depth_two_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepthTwoRel',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('relkeyword', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'depth_two_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExcludeWord',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exclude_word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleKeyword',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'google_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstaAcctInfo',
            fields=[
                ('top_post_url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('crawling_date', models.DateField()),
                ('postcontent', models.CharField(blank=True, db_column='postContent', max_length=1000, null=True)),
                ('postcomments', models.CharField(blank=True, db_column='postComments', max_length=2000, null=True)),
                ('imgsrc', models.CharField(blank=True, db_column='imgSrc', max_length=500, null=True)),
                ('likes', models.CharField(blank=True, max_length=50, null=True)),
                ('postuploaddate', models.CharField(blank=True, db_column='postUploadDate', max_length=50, null=True)),
                ('instaid', models.CharField(blank=True, db_column='instaId', max_length=50, null=True)),
                ('profileimage', models.CharField(blank=True, db_column='profileImage', max_length=500, null=True)),
                ('postscount', models.CharField(blank=True, db_column='postsCount', max_length=20, null=True)),
                ('followercount', models.CharField(blank=True, db_column='followerCount', max_length=20, null=True)),
                ('followingcount', models.CharField(blank=True, db_column='followingCount', max_length=20, null=True)),
            ],
            options={
                'db_table': 'insta_acct_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstaAcctRel',
            fields=[
                ('hashtag', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('top_post_url', models.CharField(max_length=255)),
                ('crawling_date', models.DateField()),
            ],
            options={
                'db_table': 'insta_acct_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstaHashtagInfo',
            fields=[
                ('hashtag', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_post', models.CharField(blank=True, max_length=50, null=True)),
                ('rel_tag_list', models.CharField(blank=True, max_length=255, null=True)),
                ('totalnum_rel_tag_post', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_tag_list', models.CharField(blank=True, max_length=255, null=True)),
                ('totalnum_auto_tag_post', models.CharField(blank=True, max_length=50, null=True)),
                ('crawling_date', models.DateField()),
                ('top_post_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'insta_hashtag_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JamesKeywordNaverapi',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('relkeyword', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('pcclick', models.IntegerField(blank=True, db_column='pcClick', null=True)),
                ('mobileclick', models.IntegerField(blank=True, db_column='mobileClick', null=True)),
                ('pcadsclick', models.FloatField(blank=True, db_column='pcAdsClick', null=True)),
                ('mobileadsclick', models.FloatField(blank=True, db_column='mobileAdsClick', null=True)),
                ('pcpercentage', models.FloatField(blank=True, db_column='pcPercentage', null=True)),
                ('mobilepercentage', models.FloatField(blank=True, db_column='mobilePercentage', null=True)),
                ('avgdepth', models.IntegerField(blank=True, db_column='AvgDepth', null=True)),
                ('compidx', models.CharField(blank=True, db_column='compIdx', max_length=10, null=True)),
            ],
            options={
                'db_table': 'james_keyword_naverapi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JamesMainKeywordRel',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_keyword', models.CharField(max_length=50)),
                ('relkeyword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'james_main_keyword_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCountDevice',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pc', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_count_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCountDeviceD3',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pc', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_count_device_d3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCountGenderAge',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('age0_12', models.IntegerField(blank=True, null=True)),
                ('age13_19', models.IntegerField(blank=True, null=True)),
                ('age20_24', models.IntegerField(blank=True, null=True)),
                ('age25_29', models.IntegerField(blank=True, null=True)),
                ('age30_39', models.IntegerField(blank=True, null=True)),
                ('age40_49', models.IntegerField(blank=True, null=True)),
                ('age50_field', models.IntegerField(blank=True, db_column='age50_', null=True)),
            ],
            options={
                'db_table': 'view_count_gender_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCountGenderAgeD3',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('age0_12', models.IntegerField(blank=True, null=True)),
                ('age13_19', models.IntegerField(blank=True, null=True)),
                ('age20_24', models.IntegerField(blank=True, null=True)),
                ('age25_29', models.IntegerField(blank=True, null=True)),
                ('age30_39', models.IntegerField(blank=True, null=True)),
                ('age40_49', models.IntegerField(blank=True, null=True)),
                ('age50_field', models.IntegerField(blank=True, db_column='age50_', null=True)),
            ],
            options={
                'db_table': 'view_count_gender_age_d3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeptAndKeyword',
            fields=[
                ('dept', models.ForeignKey(db_column='dept', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hospital.Department')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dept_and_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleRelkeyword',
            fields=[
                ('keyword', models.ForeignKey(db_column='keyword', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='google_keyword', serialize=False, to='hospital.GoogleKeyword')),
            ],
            options={
                'db_table': 'google_relkeyword',
                'managed': False,
            },
        ),
    ]
